import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { avatarColor, avatarInitial, shortenPeerId } from '../lib/utils';
/** Discord-like right sidebar: online members + blocked users */
export function MemberList({ peers, currentUser, blocked = new Set(), onUnblock }) {
    const peerList = Array.from(new Set(peers)).sort();
    const hasCurrent = Boolean(currentUser?.trim());
    const totalOnline = peerList.length + (hasCurrent ? 1 : 0);
    return (_jsxs("aside", { className: "member-list", children: [_jsx("div", { className: "member-list-header", children: _jsxs("span", { className: "label", children: ["Online \u2014 ", totalOnline] }) }), peerList.length === 0 && totalOnline > 0 && (_jsx("p", { className: "member-list-hint", children: "No other nodes connected. Run another node on the same network, or add its address to bootstrap_nodes in config." })), _jsxs("ul", { className: "member-list-items", children: [hasCurrent && (_jsxs("li", { className: "member-item member-item--you", children: [_jsx("span", { className: "member-avatar", style: { backgroundColor: avatarColor(currentUser) }, children: avatarInitial(currentUser) }), _jsx("span", { className: "member-name", children: currentUser }), _jsx("span", { className: "member-badge", children: "You" })] })), peerList.map(peer => (_jsxs("li", { className: "member-item", title: peer, children: [_jsx("span", { className: "member-avatar", style: { backgroundColor: avatarColor(peer) }, children: avatarInitial(peer) }), _jsx("span", { className: "member-status", title: "Online" }), _jsx("span", { className: "member-name", children: shortenPeerId(peer) })] }, peer)))] }), peerList.length === 0 && !hasCurrent && (_jsx("p", { className: "member-list-empty", children: "No other peers online. Invite others to join your grid." })), blocked.size > 0 && (_jsxs("div", { className: "blocked-section", children: [_jsx("div", { className: "member-list-header", children: _jsxs("span", { className: "label", children: ["Blocked \u2014 ", blocked.size] }) }), _jsx("ul", { className: "member-list-items", children: Array.from(blocked).map(author => (_jsxs("li", { className: "member-item", children: [_jsx("span", { className: "member-avatar", style: { backgroundColor: avatarColor(author) }, children: avatarInitial(author) }), _jsx("span", { className: "member-name", children: author }), onUnblock && (_jsx("button", { type: "button", className: "member-unblock", onClick: () => onUnblock(author), title: "Unblock", children: "Unblock" }))] }, author))) })] }))] }));
}
